### ISSUE TITLE
Set documentation path

### ISSUE THREAD

**Issue by henyxia** [open-bastion/open-bastion#4]
Once #3 finished, we will need to set where to store these files

**Comment by Fraise** [comment]
If we do not need to modify the default community health files, we could use them as they are displayed by default.

If we want to include our own version, I suggest we create a global .github repo for the organisation (as opposed to adding its own files to the open-bastion repository).

**Comment by henyxia** [comment]
How about `CONTRIBUTING` and `CHANGELOG` on root directory and `ISSUE_TEMPLATE` in `.github`?

**Comment by Fraise** [comment]
> How about `CONTRIBUTING` and `CHANGELOG` on root directory and `ISSUE_TEMPLATE` in `.github`?

CHANGELOG in the root directory is good, however I feel that CONTRIBUTING should be in the .github repo if it is standard accross all repos?

**Comment by henyxia** [comment]
Okey, let's put the `CONTRIBUTING` file in the .github on the `open-bastion` repo as long as their not more than one repo.
