### ISSUE TITLE
Choose real world examples

### ISSUE THREAD

**Issue by henyxia** [open-bastion/open-bastion#8]
To help the incoming architectural design, it would be great to choose some real world use cases.
I suggest using the following three ones:
* ingress client: ssh + egress client: ssh
* ingress client: ssh + egress client: mosh
* ingress client: mosh + egress client: ssh

Do you think of any other good use case we should add?

**Comment by Fraise** [comment]
Should we consider adding telnet as an egress client?

**Comment by henyxia** [comment]
Yes my bad, I should have added more details.
Using telnet as an egress client could be useful as some network equipment needs it.
